Add component page
js-tasks-ru/htmlcss-20220120_alexander-kuimov pull request #16
Opened 2022-02-09 15:03 UTC by Alex-Kuimov

2022-02-09 15:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-09 16:43 UTC, GSemikozov requested changes

2022-02-09 16:43 UTC, GSemikozov commented on components/content/content.css
> +.content h3 {
селекторы тегов в БЭМ не используем)

2022-02-09 16:43 UTC, GSemikozov commented on components/content/content.css
> +    height: 746px;
не стоит фиксировать высоту

2022-02-09 16:43 UTC, GSemikozov commented on components/content/content.css
> +    width: calc(100% - 381px);
ширина пусть определяется через родителя

2022-02-09 16:43 UTC, GSemikozov commented on components/footer/footer.css
> +.footer h5 {
и тут)

2022-02-09 16:43 UTC, GSemikozov commented on components/footer/footer.css
> +.page-component .footer {
по БЭМ если хотим миксовать, то .page-component__footer, но я бы советовал паддинги оставить как есть, в уже имеющемся компоненте, а если надо изменить фон - тогда задать модификатор футеру

2022-02-09 16:43 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar h4 {
исправим на класс

2022-02-09 16:43 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar a {
на класс

2022-02-09 16:43 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar__menu__item {
.sidebar__menu__item -> .sidebar__menu-item

2022-02-09 16:43 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar__menu__item-active a {
.sidebar__menu__item-active a -> .sidebar__menu-item_active

2022-02-10 06:29 UTC, Alex-Kuimov commented on components/content/content.css
> +.content h3 {
Исправил

2022-02-10 06:29 UTC, Alex-Kuimov commented on components/footer/footer.css
> +.footer h5 {
Исправил

2022-02-10 06:29 UTC, Alex-Kuimov commented on components/sidebar/sidebar.css
> +.sidebar h4 {
Исправил

2022-02-10 06:29 UTC, Alex-Kuimov commented on components/sidebar/sidebar.css
> +.sidebar a {
Исправил

2022-02-10 06:32 UTC, Alex-Kuimov commented on components/sidebar/sidebar.css
> +.sidebar__menu__item {
Исправил

2022-02-10 06:32 UTC, Alex-Kuimov commented on components/sidebar/sidebar.css
> +.sidebar__menu__item-active a {
Исправил

2022-02-10 06:43 UTC, Alex-Kuimov commented on components/footer/footer.css
> +.page-component .footer {
Исправил

2022-02-10 06:55 UTC, Alex-Kuimov commented on components/content/content.css
> +    height: 746px;
Исправил

2022-02-10 06:55 UTC, Alex-Kuimov commented on components/content/content.css
> +    width: calc(100% - 381px);
Исправил

2022-02-10 14:41 UTC, GSemikozov requested changes

2022-02-10 14:41 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +    margin-right: 56px;
на уровне блока марджины не задаем

2022-02-10 15:58 UTC, Alex-Kuimov commented on components/sidebar/sidebar.css
> +    margin-right: 56px;
Исправил

2022-02-10 16:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-10 20:29 UTC, GSemikozov approved these changes

2022-02-10 20:29 UTC, merged