Add homework 7-1
js-tasks-ru/htmlcss-20220120_alexander-kuimov pull request #17
Opened 2022-02-11 07:47 UTC by Alex-Kuimov

2022-02-11 07:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-11 19:22 UTC, GSemikozov requested changes

2022-02-11 19:22 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-wrapper {
эх) что делать с вспомогательными стили - знаем ;)

2022-02-12 09:10 UTC, Alex-Kuimov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-wrapper {
Знаем)) Сделал!

2022-02-12 11:53 UTC, GSemikozov approved these changes

2022-02-12 11:53 UTC, merged